apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-create-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-create-namespaces-binding
subjects:
- kind: ServiceAccount
  name: jenkins-robot
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-create-namespaces
  apiGroup: rbac.authorization.k8s.io
